CONTIKI_PROJECT = hello-world blink-hello timer-test sensors-demo

DEFINES+=MODELS_CONF_CC2531_USB_STICK=1

all: $(CONTIKI_PROJECT) 

CONTIKI = ../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
